server:
  port: 9099
spring:
#  redis:
#    host: 192.168.1.22   #Redis服务器地址
#    port: 6379           #Redis服务器连接端口
#    database: 0          #Redis数据库索引（默认为0）
#    timeout: 1800000     #连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 20   #连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1     #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5      #连接池中的最大空闲连接
#        min-idle: 0      #连接池中的最小空闲连接
  redis:
    database: 0
    timeout: 10000
    cluster:
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: 192.168.1.22:6379,192.168.1.22:6380,192.168.1.22:6381,192.168.1.22:6389,192.168.1.22:6390,192.168.1.22:6391
      lettuce:
        pool:
          max-active: 20   #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1     #最大阻塞等待时间(负数表示没限制)
          max-idle: 5      #连接池中的最大空闲连接
          min-idle: 0      #连接池中的最小空闲连接


